/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hrm.ui;

import hrm.Utils;
import hrm.entity.Dept;
import hrm.entity.Employee;
import java.beans.Beans;
import java.util.List;
import javax.persistence.Query;
import javax.swing.JOptionPane;

/**
 *
 * @author DIDIN
 */
public class EmpFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form EmpFrame
     */
    public EmpFrame() {
        initComponents();
        if (!Beans.isDesignTime()) {
            empEM.getTransaction().begin();
        }
        util.disabledForm(formPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        empEM = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("HrmPU").createEntityManager();
        deptQuery = java.beans.Beans.isDesignTime() ? null : empEM.createQuery("SELECT d FROM Dept d");
        deptList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(deptQuery.getResultList());
        searchPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        findbaseCombo = new javax.swing.JComboBox();
        findText = new javax.swing.JTextField();
        findButton = new javax.swing.JButton();
        formPanel = new javax.swing.JPanel();
        nikLabel = new javax.swing.JLabel();
        namaLabel = new javax.swing.JLabel();
        deptLabel = new javax.swing.JLabel();
        nikText = new javax.swing.JTextField();
        namaText = new javax.swing.JTextField();
        rfidLabel = new javax.swing.JLabel();
        rfidText = new javax.swing.JTextField();
        jabLabel = new javax.swing.JLabel();
        reguLabel = new javax.swing.JLabel();
        deptCombo = new javax.swing.JComboBox();
        jabCombo = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        tgllahirLabel = new javax.swing.JLabel();
        tlahirText = new javax.swing.JTextField();
        tlahirDate = new com.toedter.calendar.JDateChooser();
        alamatLabel = new javax.swing.JLabel();
        alamatText = new javax.swing.JTextField();
        rtLabel = new javax.swing.JLabel();
        rwText = new javax.swing.JTextField();
        rwLabel = new javax.swing.JLabel();
        rtText = new javax.swing.JTextField();
        kelLabel = new javax.swing.JLabel();
        kelText = new javax.swing.JTextField();
        kecLabel = new javax.swing.JLabel();
        kecText = new javax.swing.JTextField();
        kotaLabel = new javax.swing.JLabel();
        kotaText = new javax.swing.JTextField();
        propinsiLabel = new javax.swing.JLabel();
        propinsiText = new javax.swing.JTextField();
        posLabel = new javax.swing.JLabel();
        posText = new javax.swing.JTextField();
        telLabel = new javax.swing.JLabel();
        telText = new javax.swing.JTextField();
        hpLabel = new javax.swing.JLabel();
        hpText = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        emailText = new javax.swing.JTextField();
        ktpLabel = new javax.swing.JLabel();
        ktpText = new javax.swing.JTextField();
        golLabel = new javax.swing.JLabel();
        golText = new javax.swing.JTextField();
        tinggiLabel = new javax.swing.JLabel();
        tinggiText = new javax.swing.JTextField();
        beratLabel = new javax.swing.JLabel();
        beratText = new javax.swing.JTextField();
        aktifLabel = new javax.swing.JLabel();
        aktifCheck = new javax.swing.JCheckBox();
        reguCombo = new javax.swing.JComboBox();
        bahasaButton = new javax.swing.JButton();
        pendidikanButton = new javax.swing.JButton();
        pekerjaanButton = new javax.swing.JButton();
        keluargaButton = new javax.swing.JButton();
        controlPanel = new javax.swing.JPanel();
        saveButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        newButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Data Karyawan");

        searchPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Cari Karyawan Berdasarkan");

        findbaseCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "NIK", "Nama" }));

        findButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hrm/ui/icons/search-red-icon.png"))); // NOI18N
        findButton.setText("Cari");
        findButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(findbaseCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(findText, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(findButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(findbaseCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(findText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(findButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        formPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        nikLabel.setText("NIK");

        namaLabel.setText("Nama");

        deptLabel.setText("Dept");

        rfidLabel.setText("RFID");

        jabLabel.setText("Jabatan");

        reguLabel.setText("Regu");

        deptCombo.setEditable(true);

        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, deptList, deptCombo);
        bindingGroup.addBinding(jComboBoxBinding);

        jabCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ANGGOTA", "SEKWAN", "WADAN REGU", "DAN REGU", "WADAN UNIT", "DAN UNIT", "WADAN SEKTOR", "DAN SEKTOR", "STAFF", "SUPERVISOR", "MANAGER", "DIREKTUR" }));

        jLabel7.setText("Tempat Lahir");

        tgllahirLabel.setText("Tgl Lahir");

        alamatLabel.setText("Alamat");

        rtLabel.setText("RT");

        rwLabel.setText("RW");

        kelLabel.setText("Kelurahan");

        kecLabel.setText("Kecamatan");

        kotaLabel.setText("Kota");

        propinsiLabel.setText("Propinsi");

        posLabel.setText("Kode POS");

        telLabel.setText("Telepon");

        hpLabel.setText("HP");

        emailLabel.setText("Email");

        ktpLabel.setText("KTP/SIM");

        golLabel.setText("Gol Darah");

        tinggiLabel.setText("Tinggi");

        beratLabel.setText("Berat");

        aktifLabel.setText("Aktif");

        reguCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        bahasaButton.setText("Bahasa");

        pendidikanButton.setText("Pendidikan");

        pekerjaanButton.setText("Pekerjaan");

        keluargaButton.setText("Keluarga");

        javax.swing.GroupLayout formPanelLayout = new javax.swing.GroupLayout(formPanel);
        formPanel.setLayout(formPanelLayout);
        formPanelLayout.setHorizontalGroup(
            formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPanelLayout.createSequentialGroup()
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formPanelLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(aktifCheck)
                        .addGap(0, 670, Short.MAX_VALUE))
                    .addGroup(formPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(aktifLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ktpLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(telLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(kotaLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rtLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(alamatLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(deptLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(namaLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nikLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(26, 26, 26)
                        .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(formPanelLayout.createSequentialGroup()
                                    .addComponent(nikText, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(87, 87, 87)
                                    .addComponent(rfidLabel))
                                .addGroup(formPanelLayout.createSequentialGroup()
                                    .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(formPanelLayout.createSequentialGroup()
                                            .addComponent(tlahirText, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(tgllahirLabel))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, formPanelLayout.createSequentialGroup()
                                            .addComponent(deptCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(37, 37, 37)
                                            .addComponent(jabLabel)))
                                    .addGap(18, 18, 18)
                                    .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jabCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tlahirDate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(formPanelLayout.createSequentialGroup()
                                    .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(formPanelLayout.createSequentialGroup()
                                            .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(formPanelLayout.createSequentialGroup()
                                                    .addComponent(kotaText)
                                                    .addGap(174, 174, 174))
                                                .addGroup(formPanelLayout.createSequentialGroup()
                                                    .addComponent(rwText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(0, 0, Short.MAX_VALUE))
                                                .addGroup(formPanelLayout.createSequentialGroup()
                                                    .addComponent(telText)
                                                    .addGap(141, 141, 141)))
                                            .addGap(83, 83, 83)
                                            .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(emailLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(posLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(kecLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(beratLabel, javax.swing.GroupLayout.Alignment.TRAILING)))
                                        .addGroup(formPanelLayout.createSequentialGroup()
                                            .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(ktpText, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(formPanelLayout.createSequentialGroup()
                                                    .addGap(64, 64, 64)
                                                    .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(formPanelLayout.createSequentialGroup()
                                                            .addComponent(golLabel)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(golText, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(31, 31, 31)
                                                            .addComponent(tinggiLabel)
                                                            .addGap(18, 18, 18)
                                                            .addComponent(tinggiText, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(formPanelLayout.createSequentialGroup()
                                                            .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addGroup(formPanelLayout.createSequentialGroup()
                                                                    .addComponent(rwLabel)
                                                                    .addGap(18, 18, 18)
                                                                    .addComponent(rtText, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addGap(30, 30, 30)
                                                                    .addComponent(kelLabel))
                                                                .addComponent(propinsiLabel)
                                                                .addComponent(hpLabel))
                                                            .addGap(18, 18, 18)
                                                            .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(propinsiText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                                                .addComponent(kelText, javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addComponent(hpText))))))
                                            .addGap(73, 73, 73)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(kecText, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                        .addComponent(posText)
                                        .addComponent(emailText)
                                        .addComponent(beratText, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(alamatText))
                            .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(rfidText, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(namaText, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(formPanelLayout.createSequentialGroup()
                                    .addComponent(reguLabel)
                                    .addGap(18, 18, 18)
                                    .addComponent(reguCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bahasaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pendidikanButton, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(pekerjaanButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(keluargaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        formPanelLayout.setVerticalGroup(
            formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(nikLabel)
                    .addComponent(nikText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rfidLabel)
                    .addComponent(rfidText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bahasaButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaLabel)
                    .addComponent(namaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pendidikanButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deptLabel)
                    .addComponent(deptCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jabLabel)
                    .addComponent(jabCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reguLabel)
                    .addComponent(reguCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pekerjaanButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tlahirDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tlahirText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tgllahirLabel)))
                    .addComponent(keluargaButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alamatLabel)
                    .addComponent(alamatText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(rwText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rtLabel)
                    .addComponent(kelLabel)
                    .addComponent(kelText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rwLabel)
                    .addComponent(rtText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kecLabel)
                    .addComponent(kecText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(kotaLabel)
                    .addComponent(posText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(posLabel)
                    .addComponent(propinsiText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kotaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(propinsiLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel)
                    .addComponent(hpText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hpLabel)
                    .addComponent(telText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(beratText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(beratLabel)
                    .addComponent(tinggiText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tinggiLabel)
                    .addComponent(golText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ktpLabel)
                    .addComponent(golLabel)
                    .addComponent(ktpText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(aktifLabel)
                    .addComponent(aktifCheck))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        controlPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hrm/ui/icons/Save-icon.png"))); // NOI18N
        saveButton.setText("Simpan");
        saveButton.setEnabled(false);
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hrm/ui/icons/Misc-Delete-Database-icon.png"))); // NOI18N
        deleteButton.setText("Hapus");
        deleteButton.setEnabled(false);

        newButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hrm/ui/icons/Misc-New-Database-icon.png"))); // NOI18N
        newButton.setText("Baru");
        newButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newButtonActionPerformed(evt);
            }
        });

        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/hrm/ui/icons/button-round-cancel-icon.png"))); // NOI18N
        cancelButton.setText("Batal");
        cancelButton.setEnabled(false);
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(newButton)
                .addGap(18, 18, 18)
                .addComponent(deleteButton)
                .addGap(18, 18, 18)
                .addComponent(saveButton)
                .addGap(18, 18, 18)
                .addComponent(cancelButton)
                .addGap(33, 33, 33))
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(deleteButton)
                    .addComponent(newButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(formPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(controlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(formPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(controlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        util.enabledForm(formPanel);
        util.disabledForm(searchPanel);
        nikText.requestFocusInWindow();
        saveButton.setEnabled(true);
        deleteButton.setEnabled(true);
        cancelButton.setEnabled(true);
    }//GEN-LAST:event_newButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        util.disabledForm(formPanel);
        util.enabledForm(searchPanel);
        util.clearForm(formPanel);
        saveButton.setEnabled(false);
        deleteButton.setEnabled(false);
        cancelButton.setEnabled(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        if (empid != null) {
            if (!empEM.getTransaction().isActive()) {
                empEM.getTransaction().begin();
            }
            Employee emp = empEM.find(Employee.class, empid);
            emp.setAlamat(alamatText.getText());
            if (!beratText.getText().isEmpty()) {
                emp.setBerat(Integer.parseInt(beratText.getText()));
            }
            emp.setDept((Dept) deptCombo.getSelectedItem());
            emp.setEmail(emailText.getText());
            emp.setGoldarah(golText.getText());
            emp.setHp(hpText.getText());
            emp.setIdentitas(ktpText.getText());
            emp.setJabatan(jabCombo.getSelectedItem().toString());
            emp.setKecamatan(kecText.getText());
            emp.setKelurahan(kelText.getText());
            emp.setKodepos(posText.getText());
            emp.setKota(kotaText.getText());
            emp.setNama(namaText.getText());
            emp.setNik(nikText.getText());
            emp.setPropinsi(propinsiText.getText());
            if (!reguCombo.getSelectedItem().toString().isEmpty()) {
                emp.setRegu(Integer.parseInt(reguCombo.getSelectedItem().toString()));
            }
            emp.setRfid(rfidText.getText());
            emp.setRt(rtText.getText());
            emp.setRw(rwText.getText());
            boolean status;
            if (aktifCheck.isSelected()) {
                status = true;
            } else {
                status = false;
            }
            emp.setStatus(status);
            emp.setTelepon(telText.getText());
            emp.setTempatlahir(tlahirText.getText());
            emp.setTgllahir(tlahirDate.getDate());
            if (!tinggiText.getText().isEmpty()) {
                emp.setTinggi(Integer.parseInt(tinggiText.getText()));
            }
            empEM.getTransaction().commit();
            JOptionPane.showMessageDialog(null, "Data " + namaText.getText() + " telah di update");
            util.clearForm(formPanel);
            util.disabledForm(formPanel);
            util.enabledForm(searchPanel);
            saveButton.setEnabled(false);
            deleteButton.setEnabled(false);
            cancelButton.setEnabled(false);
        } else {
            if (!empEM.getTransaction().isActive()) {
                empEM.getTransaction().begin();
            }
            Employee emp = new Employee();
            emp.setAlamat(alamatText.getText());
            if (!beratText.getText().isEmpty()) {
                emp.setBerat(Integer.parseInt(beratText.getText()));
            }
            emp.setDept((Dept) deptCombo.getSelectedItem());
            emp.setEmail(emailText.getText());
            emp.setGoldarah(golText.getText());
            emp.setHp(hpText.getText());
            emp.setIdentitas(ktpText.getText());
            emp.setJabatan(jabCombo.getSelectedItem().toString());
            emp.setKecamatan(kecText.getText());
            emp.setKelurahan(kelText.getText());
            emp.setKodepos(posText.getText());
            emp.setKota(kotaText.getText());
            emp.setNama(namaText.getText());
            emp.setNik(nikText.getText());
            emp.setPropinsi(propinsiText.getText());
            if (!reguCombo.getSelectedItem().toString().isEmpty()) {
                emp.setRegu(Integer.parseInt(reguCombo.getSelectedItem().toString()));
            }
            emp.setRfid(rfidText.getText());
            emp.setRt(rtText.getText());
            emp.setRw(rwText.getText());
            boolean status;
            if (aktifCheck.isSelected()) {
                status = true;
            } else {
                status = false;
            }
            emp.setStatus(status);
            emp.setTelepon(telText.getText());
            emp.setTempatlahir(tlahirText.getText());
            emp.setTgllahir(tlahirDate.getDate());
            if (!tinggiText.getText().isEmpty()) {
                emp.setTinggi(Integer.parseInt(tinggiText.getText()));
            }
            empEM.persist(emp);
            empEM.getTransaction().commit();
            JOptionPane.showMessageDialog(null, "Data Karyawan telah di Simpan");
            util.clearForm(formPanel);
            util.disabledForm(formPanel);
            util.enabledForm(searchPanel);
            saveButton.setEnabled(false);
            deleteButton.setEnabled(false);
            cancelButton.setEnabled(false);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void findButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findButtonActionPerformed
        String findQueryText = null;
        if (findbaseCombo.getSelectedItem() == "NIK") {
            findQueryText = "SELECT e FROM Employee e WHERE e.nik LIKE '%" + findText.getText().trim() + "%'";
        }
        if (findbaseCombo.getSelectedItem() == "Nama") {
            findQueryText = "SELECT e FROM Employee e WHERE e.nama LIKE '%" + findText.getText().trim() + "%'";
        }
        Query findQuery = empEM.createQuery(findQueryText);
        List<Employee> emp = (List<Employee>) findQuery.getResultList();
        if (emp.size() > 1) {
            Employee e = (Employee) JOptionPane.showInputDialog(this, closable, "Hasil Pencarian", WIDTH, null, emp.toArray(), isSelected);
            util.clearForm(formPanel);
            util.disabledForm(searchPanel);
            util.enabledForm(formPanel);
            saveButton.setEnabled(true);
            deleteButton.setEnabled(true);
            cancelButton.setEnabled(true);
            alamatText.setText(e.getAlamat());
            if (e.isStatus() == true) {
                aktifCheck.setSelected(true);
            }
            beratText.setText(e.getBerat().toString());
            emailText.setText(e.getEmail());
            golText.setText(e.getGoldarah());
            hpText.setText(e.getHp());
            jabCombo.setSelectedItem(e.getJabatan());
            kecText.setText(e.getKecamatan());
            kelText.setText(e.getKelurahan());
            kotaText.setText(e.getKota());
            ktpText.setText(e.getIdentitas());
            namaText.setText(e.getNama());
            nikText.setText(e.getNik());
            posText.setText(e.getKodepos());
            propinsiText.setText(e.getPropinsi());
            rfidText.setText(e.getRfid());
            rtText.setText(e.getRt());
            rwText.setText(e.getRw());
            telText.setText(e.getTelepon());
            tinggiText.setText(e.getTinggi().toString());
            tlahirText.setText(e.getTempatlahir());
            tlahirDate.setDate(e.getTgllahir());
            deptCombo.setSelectedItem(e.getDept().getNamadept().toString());
            empid = e.getId();
        }
        if (emp.size() == 1) {
            util.clearForm(formPanel);
            util.disabledForm(searchPanel);
            util.enabledForm(formPanel);
            saveButton.setEnabled(true);
            deleteButton.setEnabled(true);
            cancelButton.setEnabled(true);
            for (Employee e : emp) {
                alamatText.setText(e.getAlamat());
                if (e.isStatus() == true) {
                    aktifCheck.setSelected(true);
                }
                beratText.setText(e.getBerat().toString());
                emailText.setText(e.getEmail());
                golText.setText(e.getGoldarah());
                hpText.setText(e.getHp());
                jabCombo.setSelectedItem(e.getJabatan());
                kecText.setText(e.getKecamatan());
                kelText.setText(e.getKelurahan());
                kotaText.setText(e.getKota());
                ktpText.setText(e.getIdentitas());
                namaText.setText(e.getNama());
                nikText.setText(e.getNik());
                posText.setText(e.getKodepos());
                propinsiText.setText(e.getPropinsi());
                rfidText.setText(e.getRfid());
                rtText.setText(e.getRt());
                rwText.setText(e.getRw());
                telText.setText(e.getTelepon());
                tinggiText.setText(e.getTinggi().toString());
                tlahirText.setText(e.getTempatlahir());
                tlahirDate.setDate(e.getTgllahir());
                deptCombo.setSelectedItem(e.getDept().getNamadept().toString());
                empid = e.getId();
            }
        }
    }//GEN-LAST:event_findButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox aktifCheck;
    private javax.swing.JLabel aktifLabel;
    private javax.swing.JLabel alamatLabel;
    private javax.swing.JTextField alamatText;
    private javax.swing.JButton bahasaButton;
    private javax.swing.JLabel beratLabel;
    private javax.swing.JTextField beratText;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JComboBox deptCombo;
    private javax.swing.JLabel deptLabel;
    private java.util.List<hrm.entity.Dept> deptList;
    private javax.persistence.Query deptQuery;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailText;
    private javax.persistence.EntityManager empEM;
    private javax.swing.JButton findButton;
    private javax.swing.JTextField findText;
    private javax.swing.JComboBox findbaseCombo;
    private javax.swing.JPanel formPanel;
    private javax.swing.JLabel golLabel;
    private javax.swing.JTextField golText;
    private javax.swing.JLabel hpLabel;
    private javax.swing.JTextField hpText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox jabCombo;
    private javax.swing.JLabel jabLabel;
    private javax.swing.JLabel kecLabel;
    private javax.swing.JTextField kecText;
    private javax.swing.JLabel kelLabel;
    private javax.swing.JTextField kelText;
    private javax.swing.JButton keluargaButton;
    private javax.swing.JLabel kotaLabel;
    private javax.swing.JTextField kotaText;
    private javax.swing.JLabel ktpLabel;
    private javax.swing.JTextField ktpText;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JTextField namaText;
    private javax.swing.JButton newButton;
    private javax.swing.JLabel nikLabel;
    private javax.swing.JTextField nikText;
    private javax.swing.JButton pekerjaanButton;
    private javax.swing.JButton pendidikanButton;
    private javax.swing.JLabel posLabel;
    private javax.swing.JTextField posText;
    private javax.swing.JLabel propinsiLabel;
    private javax.swing.JTextField propinsiText;
    private javax.swing.JComboBox reguCombo;
    private javax.swing.JLabel reguLabel;
    private javax.swing.JLabel rfidLabel;
    private javax.swing.JTextField rfidText;
    private javax.swing.JLabel rtLabel;
    private javax.swing.JTextField rtText;
    private javax.swing.JLabel rwLabel;
    private javax.swing.JTextField rwText;
    private javax.swing.JButton saveButton;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JLabel telLabel;
    private javax.swing.JTextField telText;
    private javax.swing.JLabel tgllahirLabel;
    private javax.swing.JLabel tinggiLabel;
    private javax.swing.JTextField tinggiText;
    private com.toedter.calendar.JDateChooser tlahirDate;
    private javax.swing.JTextField tlahirText;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
    private Utils util = new Utils();
    private Long empid = null;
}
